//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adress_contragent
    {
        public int id_adr_contr { get; set; }
        public int id_contragent { get; set; }
        public int id_conec_adress { get; set; }
    
        public virtual Con_adress_Point Con_adress_Point { get; set; }
    }
}
