//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contragenti_contact
    {
        public int id_contr_cont { get; set; }
        public int id_contrag { get; set; }
        public int id_contact { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Contragenti Contragenti { get; set; }
    }
}
