//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documents()
        {
            this.Dvijenie_Documenta = new HashSet<Dvijenie_Documenta>();
        }
    
        public int id_doc { get; set; }
        public int id_tip_doc { get; set; }
        public string name_doc { get; set; }
        public int id_otd { get; set; }
        public int id_vid_doc { get; set; }
        public int id_sotrud_from { get; set; }
        public int id_sotrud_to { get; set; }
    
        public virtual Otdely Otdely { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
        public virtual Sotrudniki Sotrudniki1 { get; set; }
        public virtual Tip_Documenta Tip_Documenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dvijenie_Documenta> Dvijenie_Documenta { get; set; }
    }
}
