//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudniki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrudniki()
        {
            this.Documents = new HashSet<Documents>();
            this.Documents1 = new HashSet<Documents>();
            this.History_replace_sotr = new HashSet<History_replace_sotr>();
            this.Otdely = new HashSet<Otdely>();
        }
    
        public int id_sotr { get; set; }
        public string name_sotr { get; set; }
        public string lastname_sotr { get; set; }
        public string adress_sotr { get; set; }
        public string email_sotr { get; set; }
        public string phone_sotr { get; set; }
        public int id_otd { get; set; }
        public Nullable<System.DateTime> data_priema { get; set; }
        public Nullable<int> id_dolzhn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documents> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documents> Documents1 { get; set; }
        public virtual Dolzhnosti Dolzhnosti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History_replace_sotr> History_replace_sotr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Otdely> Otdely { get; set; }
        public virtual Otdely Otdely1 { get; set; }
    }
}
