//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ulica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ulica()
        {
            this.Con_Adress_Dom = new HashSet<Con_Adress_Dom>();
        }
    
        public int id_ulica { get; set; }
        public string name_ulica { get; set; }
        public int id_mesto { get; set; }
        public string post_index_ulica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Con_Adress_Dom> Con_Adress_Dom { get; set; }
        public virtual Mestnost Mestnost { get; set; }
    }
}
